## The network files distributed with aracne.networks up to version 1.39.0
## (data/regulon*.rda, generated by prepareRegulons.R) were moved to Zenodo
## (https://doi.org/10.5281/zenodo.ZENODO_RECORD) without any modification.
## This script extracts them from the git history of the package (commit
## ccb820f, the last one containing them) and builds
## the catalog in inst/extdata/regulons.csv used by getRegulon().

## Run from the root of the git repository
outdir <- "zenodo_upload"
dir.create(outdir, showWarnings = FALSE)
files <- system2("git", c("ls-tree", "--name-only", "ccb820f", "data/"),
    stdout = TRUE)
files <- grep("\\.rda$", files, value = TRUE)
for (f in files)
    system2("git", c("show", paste0("ccb820f:", f)),
        stdout = file.path(outdir, basename(f)))

catalog <- do.call(rbind, lapply(file.path(outdir, basename(files)),
    function(f) {
        env <- new.env()
        object <- load(f, envir = env)
        regulon <- env[[object]]
        data.frame(
            network = sub("^regulon", "", object),
            object = object,
            regulators = length(regulon),
            interactions = sum(lengths(lapply(regulon, `[[`, "tfmode"))),
            file = basename(f),
            bytes = file.size(f),
            md5 = unname(tools::md5sum(f))
        )
    }))
catalog
## The tumor names and TCGA codes were then added from the original
## documentation of each data set (see prepareRegulons.R).
